### ISSUE TITLE
Ошибки методов

### ISSUE THREAD

**Issue by romzzzzec** [developeruz/shopping-cart-component#2]
`commit 0d54cdb593bad1646a42ea95834374db4e2555d1`

EShoppingCart.php:

``` php
private function add($class, $id, $quality)
    {
        $model = $this->getModel($class, $id);
        if (!empty($model) && $model->getAviable()) {
            $this->put($model, $quality);
        }
    }
```

README. md

``` php
Модели, которым необходимо дать возможность добавления в корзину,
должны реализовать интерфейс `IECartPosition`:
...
public function getAvailable()
    {
        return true;
    } 
```

Unknown Method – yii\base\UnknownMethodException:
Calling unknown method: frontend\models\Product::getAviable()

**Comment by developeruz** [comment]
Исправила опечатку в ReadMe, спасибо что нашли ее.

**Comment by romzzzzec** [comment]
вы не проверяете работоспособность?

IECartPosition.php

``` php
    public function getAvailable();
```

Class frontend\models\Product contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (developeruz\shopping\IECartPosition::getAvailable)

лучший вариант наверно будет наследовать своим классом
